# Generated by Django 4.2.19 on 2025-02-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_options_remove_post_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='post',
        ),
    ]
